const constants = {
  FILL_NAME: "FILL_NAME",
  FILL_TIME: "FILL_TIME",
  SORT_ITEMS: "SORT_BY_NAME",
  ADD_ITEM: "ADD_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  FETCH_TODO_DATA: "FETCH_TODO_DATA",
  FETCH_TODO_DATA_SUCCESS: "FETCH_TODO_DATA_SUCCESS",
  FETCH_TODO_DATA_ERROR: "FETCH_TODO_DATA_ERROR",
  SORT_USERS: "SORT_BY_NAME",
  ADD_USER: "ADD_USER",
  EDIT_USER: "EDIT_USER",
  REMOVE_USER: "REMOVE_USER"
}

export default constants;
